/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Views.QLTT;

import Utils.SVGImage;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author X1
 */
public class QLTT extends javax.swing.JInternalFrame {
    SVGImage svgSet = new SVGImage();
    /**
     * Creates new form QLSANPHAM
     */
    public QLTT() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
        setButtonIcon();
        
    }

    void setButtonIcon() {
       btnBrand.setIcon(svgSet.createSVGIcon("Images/SVG/brand.svg", 150, 150));
       btnSz.setIcon(svgSet.createSVGIcon("Images/SVG/size.svg", 150, 150));
       btnColor.setIcon(svgSet.createSVGIcon("Images/SVG/pantone.svg", 150, 150));
       btnMaterial.setIcon(svgSet.createSVGIcon("Images/SVG/material-1.svg", 150, 150));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBrand = new javax.swing.JButton();
        btnColor = new javax.swing.JButton();
        btnSz = new javax.swing.JButton();
        btnMaterial = new javax.swing.JButton();

        setBackground(new java.awt.Color(227, 241, 254));
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1090, 630));
        setMinimumSize(new java.awt.Dimension(1090, 630));
        setPreferredSize(new java.awt.Dimension(1090, 630));

        btnBrand.setFont(new java.awt.Font("Montserrat Medium", 0, 22)); // NOI18N
        btnBrand.setText("  Nhãn Hàng");
        btnBrand.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBrandMouseClicked(evt);
            }
        });

        btnColor.setFont(new java.awt.Font("Montserrat Medium", 0, 22)); // NOI18N
        btnColor.setText("  Màu Sắc ");
        btnColor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnColorMouseClicked(evt);
            }
        });

        btnSz.setFont(new java.awt.Font("Montserrat Medium", 0, 22)); // NOI18N
        btnSz.setText("  Kích Cỡ");
        btnSz.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSzMouseClicked(evt);
            }
        });

        btnMaterial.setFont(new java.awt.Font("Montserrat Medium", 0, 22)); // NOI18N
        btnMaterial.setText("  Chất Liệu");
        btnMaterial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMaterialMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnColor, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSz, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSz, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnColor, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBrandMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBrandMouseClicked
        // BRAND
        QLTT_Brand brand = new QLTT_Brand();
        brand.setVisible(true);
    }//GEN-LAST:event_btnBrandMouseClicked

    private void btnColorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnColorMouseClicked
        // CL
        QLTT_Pantone cl = new QLTT_Pantone();
        cl.setVisible(true);
    }//GEN-LAST:event_btnColorMouseClicked

    private void btnSzMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSzMouseClicked
        // SZ
        QLTT_Sz sz = new QLTT_Sz();
        sz.setVisible(true);
    }//GEN-LAST:event_btnSzMouseClicked

    private void btnMaterialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMaterialMouseClicked
        // MATERIAL
        QLTT_Material material = new QLTT_Material();
        material.setVisible(true);
    }//GEN-LAST:event_btnMaterialMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrand;
    private javax.swing.JButton btnColor;
    private javax.swing.JButton btnMaterial;
    private javax.swing.JButton btnSz;
    // End of variables declaration//GEN-END:variables
}
