/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Views;

import Services.MyChartService;
import Utils.SVGImage;
import ViewModels.DonutPieChartViewModel;
import ViewModels.PieChartModel;
import ViewModels.PieChartViewModel;
import java.awt.Color;
import java.text.DecimalFormat;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author X1
 */
public class TrangChu extends javax.swing.JInternalFrame {
    DecimalFormat formatter = new DecimalFormat("#,###");
    SVGImage svgSet = new SVGImage();
    MyChartService myService = new MyChartService();
    LocalDate currentDate = LocalDate.now();
    /**
     * Creates new form TrangChu
     */
    
    public TrangChu() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
        load();
    }
    
    void load(){
        loadCboYear(myService.showYear());
        
        int y = currentDate.getYear();        
        int m = currentDate.getMonthValue();
        updatePieChart(y, m);
        updatePieChartTop(y, m);
        updateDonutChart(y, m);
    }
    
    void loadCboYear(ArrayList<Integer> ls){
        DefaultComboBoxModel model = (DefaultComboBoxModel) cboYear.getModel();
        model.removeAllElements();
        for (Integer i : ls) {
            model.addElement(i);
        }
    }
    
    void loadCboMonth(ArrayList<Integer> ls){
        DefaultComboBoxModel model = (DefaultComboBoxModel) cboMonth.getModel();
        model.removeAllElements();
        for (Integer i : ls) {
            model.addElement(i);
        }
    }

    private Color getColor(int i){
        Color[] color = new Color[]{new Color(248, 113, 113),new Color(251, 146, 60),new Color(251, 191, 37),
                                        new Color(163, 230, 53),new Color(51, 211, 153),new Color(73, 45, 150)};
        return color[i];
    }
    
    //LOAD
    void updatePieChart(int year, int month) {
        ArrayList<PieChartViewModel> bestSellers = myService.getListBestSeller(year, month);
        int i = 0;
        for (PieChartViewModel model : bestSellers) {
            pcBestSellerM.addData(new PieChartModel(model.getTenSP(), model.getSoL(), getColor(i++))); 
        }
    }
    void updatePieChartTop(int year, int month) {
        ArrayList<PieChartViewModel> topDoanhMuc = myService.getTopSell(year, month);
        int i = 0;
        for (PieChartViewModel model : topDoanhMuc) {
            pcBestDM.addData(new PieChartModel(model.getTenDM(), model.getSoL(), getColor(i++)));
        }
    }
    void updateDonutChart(int year, int month) {
        ArrayList<DonutPieChartViewModel> topProfit = myService.getTopProfit(year, month);
        int i = 0;
        for (DonutPieChartViewModel model : topProfit) {
            donutProfit.addData(new PieChartModel(model.getTenSP(), model.getLoiN(), getColor(i++)) );
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cboYear = new javax.swing.JComboBox<>();
        cboMonth = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        donutProfit = new Utils.DonutPieChart();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        pcBestDM = new Utils.PieChart();
        pieChart6 = new Utils.PieChart();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        pcBestSellerM = new Utils.PieChart();
        pieChart5 = new Utils.PieChart();
        jPanel3 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(246, 246, 246));
        setMaximumSize(new java.awt.Dimension(1100, 680));
        setMinimumSize(new java.awt.Dimension(1100, 680));
        setPreferredSize(new java.awt.Dimension(1100, 680));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cboYear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cboYearMouseClicked(evt);
            }
        });
        getContentPane().add(cboYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 20, 134, -1));

        cboMonth.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cboMonthMouseClicked(evt);
            }
        });
        getContentPane().add(cboMonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 20, 134, -1));

        jLabel1.setText("Năm:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 20, -1, -1));

        jLabel2.setText("Tháng:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 20, -1, -1));

        jPanel1.setBackground(new java.awt.Color(246, 246, 246));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel1.setForeground(new java.awt.Color(246, 246, 246));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Top Lợi Nhuận của Tháng");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));
        jPanel1.add(donutProfit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 300, 260));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 60, 350, 280));

        jPanel2.setBackground(new java.awt.Color(246, 246, 246));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel2.setForeground(new java.awt.Color(246, 246, 246));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Top Doanh Thu của Tháng");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        pieChart6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        pcBestDM.add(pieChart6);
        pieChart6.setBounds(0, 0, 0, 0);

        jPanel2.add(pcBestDM, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 30, 330, 250));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, 350, 280));

        jPanel4.setBackground(new java.awt.Color(246, 246, 246));
        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel4.setForeground(new java.awt.Color(246, 246, 246));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Best Seller của Tháng");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        pieChart5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        pcBestSellerM.add(pieChart5);
        pieChart5.setBounds(0, 0, 0, 0);

        jPanel4.add(pcBestSellerM, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 30, 330, 250));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 350, 280));

        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 1070, 280));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboYearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboYearMouseClicked
        // YEAR
        if (cboYear.getSelectedIndex() >=0 ) {
            int y = Integer.valueOf(cboYear.getSelectedItem().toString());
            try {
                loadCboMonth(myService.showMonth(y));
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_cboYearMouseClicked

    private void cboMonthMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboMonthMouseClicked
        // MONTH
        if (cboMonth.getSelectedIndex()>=0) {
            pcBestSellerM.clearData();
            pcBestDM.clearData();
            donutProfit.clearData();
            int y = Integer.valueOf(cboYear.getSelectedItem().toString());
            int m = Integer.valueOf(cboMonth.getSelectedItem().toString());
            updatePieChart(y, m);
            updatePieChartTop(y, m);
            updateDonutChart(y, m);
        }
    }//GEN-LAST:event_cboMonthMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cboMonth;
    private javax.swing.JComboBox<String> cboYear;
    private Utils.DonutPieChart donutProfit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private Utils.PieChart pcBestDM;
    private Utils.PieChart pcBestSellerM;
    private Utils.PieChart pieChart5;
    private Utils.PieChart pieChart6;
    // End of variables declaration//GEN-END:variables
}
